### ISSUE TITLE
Oracle 11.x download is no longer available.

### ISSUE THREAD

**Issue by andynu** [yahonda/rails-dev-box#43]
Instructions for building the test environment involve downloading oracle-xe-11.2.0-1.0.x86_64.rpm.zip this does not appear to be present on Oracle's site any longer.

https://www.oracle.com/database/technologies/xe-downloads.html

- Contains version 21
- The previous version archive contains 18
- The previous version archive on version 18's page dead-ends.

It is unclear how to produce a viable test environment for the oracle-enhanced project.

**Comment by yahonda** [comment]
#44 should have fixed this issue.
